language: python

python:
  - "3.6"

sercives:
  - postgresql

before_install:
  - pip install pycodestyle

install:
  - pip install -r src/app/requirements.txt

before_script:
  - psql -c "CREATE DATABASE db_sskey;" -U postgres

script:
  - coverage run --source="src/app" -m pytest
  - coverage report --fail-under=20
  - pycodestyle src/ --ignore=E501,E402

